<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SwiperApp.Core</RootNamespace>
		<UseMaui>true</UseMaui>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\0001.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0002.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0003.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0004.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0005.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0006.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0007.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0008.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0009.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0011.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0012.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0013.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0014.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0015.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0016.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0017.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0018.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0019.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0028.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0032.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0035.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0041.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0044.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0048.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0054.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0059.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0064.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0074.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0087.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0090.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0093.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0098.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0101.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0102.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0104.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0106.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0114.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0121.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0123.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0127.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0133.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0136.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0144.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0145.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0152.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0164.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0166.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0175.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0181.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0183.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0201.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0208.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0227.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0236.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0240.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0243.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0252.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0263.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0278.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0279.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0281.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0282.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0283.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0285.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0291.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0293.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0296.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0297.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\0301.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0001.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0002.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0003.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0004.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0005.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0006.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0007.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0008.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0009.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0011.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0012.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0013.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0014.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0015.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0016.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0017.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0018.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0019.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0028.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0032.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0035.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0041.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0044.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0048.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0054.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0059.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0064.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0074.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0087.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0090.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0093.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0098.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0101.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0102.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0104.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0106.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0114.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0121.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0123.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0127.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0133.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0136.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0144.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0145.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0152.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0164.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0166.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0175.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0181.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0183.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0201.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0208.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0227.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0236.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0240.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0243.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0252.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0263.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0278.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0279.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0281.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0282.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0283.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0285.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0291.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0293.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0296.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0297.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\a_0301.jpg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Resources\Images\res\**" />
	  <EmbeddedResource Remove="Resources\Images\res\**" />
	  <MauiCss Remove="Resources\Images\res\**" />
	  <MauiImage Remove="Resources\Images\res\**" />
	  <MauiXaml Remove="Resources\Images\res\**" />
	  <None Remove="Resources\Images\res\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Raw\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Controls\SwiperControl.xaml.cs">
	    <DependentUpon>SwiperControl.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Controls\SwiperControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
