CREATE DATABASE [Books]   
  (EDITION = 'Basic',  
   SERVICE_OBJECTIVE = 'Basic',  
   MAXSIZE = 1 GB)  
   WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS; 
GO 
 
ALTER DATABASE [Books] SET COMPATIBILITY_LEVEL = 100 
GO 
 
ALTER DATABASE [Books] SET ANSI_NULL_DEFAULT OFF  
GO 
 
ALTER DATABASE [Books] SET ANSI_NULLS OFF  
GO 
 
ALTER DATABASE [Books] SET ANSI_PADDING OFF  
GO 
 
ALTER DATABASE [Books] SET ANSI_WARNINGS OFF  
GO 
 
ALTER DATABASE [Books] SET ARITHABORT OFF  
GO 
 
ALTER DATABASE [Books] SET AUTO_SHRINK OFF  
GO 
 
ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS ON  
GO 
 
ALTER DATABASE [Books] SET CURSOR_CLOSE_ON_COMMIT OFF  
GO 
 
ALTER DATABASE [Books] SET CONCAT_NULL_YIELDS_NULL OFF  
GO 
 
ALTER DATABASE [Books] SET NUMERIC_ROUNDABORT OFF  
GO 
 
ALTER DATABASE [Books] SET QUOTED_IDENTIFIER OFF  
GO 
 
ALTER DATABASE [Books] SET RECURSIVE_TRIGGERS OFF  
GO 
 
ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS_ASYNC OFF  
GO 
 
ALTER DATABASE [Books] SET DATE_CORRELATION_OPTIMIZATION OFF  
GO 
 
ALTER DATABASE [Books] SET ALLOW_SNAPSHOT_ISOLATION ON  
GO 
 
ALTER DATABASE [Books] SET PARAMETERIZATION SIMPLE  
GO 
 
ALTER DATABASE [Books] SET READ_COMMITTED_SNAPSHOT ON  
GO 
 
ALTER DATABASE [Books] SET  MULTI_USER  
GO 
 
ALTER DATABASE [Books] SET QUERY_STORE = ON 
GO 

ALTER DATABASE [Books] SET QUERY_STORE  
  (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY =  
  (STALE_QUERY_THRESHOLD_DAYS = 7),  
  DATA_FLUSH_INTERVAL_SECONDS = 900,  
  INTERVAL_LENGTH_MINUTES = 60,  
  MAX_STORAGE_SIZE_MB = 10,  
  QUERY_CAPTURE_MODE = AUTO,  
  SIZE_BASED_CLEANUP_MODE = AUTO) 
GO 
 
ALTER DATABASE [Books] SET  READ_WRITE  
GO 

USE Books 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[Books]( 
  [Id] [int] IDENTITY(1,1) NOT NULL, 
  [Title] [nvarchar](50) NOT NULL, 
  [Author] [nvarchar](50) NOT NULL, 
  [ISBN] [nvarchar](50) NULL, 
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED  
( 
  [Id] ASC 
)WITH (PAD_INDEX = OFF,  
STATISTICS_NORECOMPUTE = OFF,  
IGNORE_DUP_KEY = OFF,  
ALLOW_ROW_LOCKS = ON,  
ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 

SET IDENTITY_INSERT [dbo].[Books] ON  
GO 

INSERT [dbo].[Books] ([Id], [Title], [Author], [ISBN])  
  VALUES (1, N'Xamarin.Forms Succinctly',  
  N'Alessandro Del Sole', N'978-1-64200-175-4')
GO 

INSERT [dbo].[Books] ([Id], [Title], [Author], [ISBN])  
  VALUES (2, N'Visual Studio 2019 for Mac Succinctly',  
  N'Alessandro Del Sole', N'978-1-64200-177-8') 
GO 

SET IDENTITY_INSERT [dbo].[Books] OFF 
GO 
